[workspace]
authors = ["Ashesh Vasalya <asheshvasalya@gmail.com>"]
name = "pixi_insta360_ros2_jazzy_driver"
version = "0.1.0"
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = [{ platform = "linux-64", cuda = "12" }]
conda-pypi-map = false

[activation]
scripts = ["scripts/set_ros_env.sh", "install/setup.bash"]

# Base C++ / Build tools included in EVERY environment
[dependencies]
python = "3.12.*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
nasm = "*"
yasm = "*"
perl = "*"

[target.linux.dependencies]
libgl-devel = "*"

# -------------------------------------------------------------
# ENVIRONMENT DEFINITIONS
# -------------------------------------------------------------
[environments]
jazzy360 = { features = ["jazzy360", "dev"] }

# -------------------------------------------------------------
# FEATURE 1: ROS 2 Jazzy360
# -------------------------------------------------------------
[feature.jazzy360]
channels = ["https://prefix.dev/robostack-jazzy", "conda-forge"]

[feature.jazzy360.dependencies]
colcon-common-extensions = "*"
ros-jazzy-desktop = "*"
ros-jazzy-joint-state-publisher = ">=2.4.0,<3"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-xacro = ">=2.0.13,<3"
ros-jazzy-generate-parameter-library = "*"
rosdep = "*"
ros-jazzy-topic-tools = ">=1.3.3,<2"
ros-jazzy-topic-tools-interfaces = ">=1.3.3,<2"
ros-jazzy-camera-info-manager = "*"
ros-jazzy-cv-bridge = "*"
ros-jazzy-image-transport = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-std-srvs = "*"
ros-jazzy-imu-tools = "*"
ros-jazzy-imu-filter-madgwick = "*"
ros-jazzy-image-view = ">=5.0.11,<6"
ros-jazzy-rqt-image-view = ">=1.3.0,<2"

[feature.jazzy360.pypi-dependencies]
torch = { version = "~=2.4.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu124" }
torchaudio = { version = "*", index = "https://download.pytorch.org/whl/cu124" }

[feature.jazzy360.tasks]
update-submodules = "git submodule update --init --recursive"
build = "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev --symlink-install"
setup = { depends-on = ["update-submodules", "build"] }

ffmpeg-download = """
rm -rf external/FFmpeg external/nv-codec-headers
git clone https://github.com/FFmpeg/nv-codec-headers.git external/nv-codec-headers
git clone https://github.com/FFmpeg/FFmpeg.git external/FFmpeg
"""

ffmpeg-build = """
cd external/nv-codec-headers
make PREFIX=$CONDA_PREFIX install

cd ../FFmpeg

./configure \
    --prefix=$CONDA_PREFIX \
    --enable-shared \
    --disable-static \
    --enable-gpl \
    --enable-nonfree \
    --enable-cuda \
    --enable-ffnvcodec \
    --enable-libnpp \
    --enable-nvenc \
    --extra-cflags=-I/usr/local/cuda/include \
    --extra-ldflags=-L/usr/local/cuda/lib64

make -j$(nproc)
make install
"""

ffmpeg = { depends-on = ["ffmpeg-download", "ffmpeg-build"] }

# run these commands to install and build ffmpeg with CUDA support
# pixi update
# pixi install
# pixi run ffmpeg


# -------------------------------------------------------------
# SHARED DEV TOOLS
# -------------------------------------------------------------
[feature.dev.dependencies]
ruff = "*"
pytest = "*"
filelock = ">=3.20.3, <4"

[feature.dev.pypi-dependencies]
crisp-python = ">=3.0.0,<4"